version: '3'

services:
    database:
        build: ./database
        networks:
            - core
        volumes:
            - ./database/postgres-data:/var/lib/postgresql/data
    server:
        build: ./server
        volumes:
            - ./server:/app
        depends_on:
            - database
        ports:
            - 5001:80
        networks:
            - core
            - site
    site:
        build: ./site
        volumes:
            - ./site:/site
        ports:
            - 5000:3000
        depends_on: 
            - server
        networks:
            - site

networks:
    core:
        driver: bridge

    site:
        driver: bridge